### ISSUE TITLE
[Important] Compare to STOA

### ISSUE THREAD

**Issue by Autotalker** [QVPR/Patch-NetVLAD#1]
Hi, 

First, thank you for your contribution and congratulations!

I would have a question here, concerning Table 1 and Table 2 in your paper.

I think the true STOA methods are missing here. Please refer to Table 1 in the paper [Self-supervising Fine-grained Region Similarities for Large-scale Image Localization]

Adding the full results to Table 1 would make this paper friendly to follow up works.

Furthermore, when I check Table 2, I get the info. that the reported numbers of the proposed method are based on the usage of RANSAC, known as Ours (Multi-RANSAC-Patch-NetVLAD).

I strongly expect a fair comparison as the reported recalls of ALL methods in the paper [Self-supervising Fine-grained Region Similarities for Large-scale Image Localization] did not use RANSAC.

It is well-known that using RANSAC [two-view matching] can boost recalls. To validate the effectiveness of the proposed `Patch-NetVLAD' descriptor, please refrain from using RANSAC or using RANSAC for all baseline descriptors of STOA methods.

Please make fair comparisons.

Last, even for the out-of-the-date Netvlad baseline, its recalls on the Tokyo 24/7 are much better than the numbers reported in your paper. Please refer to Table 1 in the paper [Self-supervising Fine-grained Region Similarities for Large-scale Image Localization]

Please reflect these changes to your Arxiv and final version. 

Without comparing to true STOA methods, the contribution of the proposed `Patch-NetVLAD' is questionable.

Congratulations again!

**Comment by Tobias-Fischer** [comment]
Dear @Autotalker,

Many thanks for your interest in our work, and thank you for your congratulations!This GitHub repository is for the (upcoming) code of Patch-NetVLAD, and the Issues tracker here is meant for reporting questions/bugs related to the code only (see https://guides.github.com/features/issues/).

Re. the research itself - we have received a lot of useful feedback and suggestions including yours and will try to incorporate as much as is possible into the revision, as well as in future work - noting that due to the constraints of the process we are unlikely to be able to do it all in this specific publication.


Many wishes,Tobias

P.S. Please note that we may not reply to anonymous emails as they are likely to be filtered out by our university’s spam filter (mentioning this as you inadvertently created an anonymous account here on GitHub when you posted this issue – fresh email addresses might be filtered out and non-anonymous communication is our preferred means of talking about scientific questions).

You are welcome to send me an email (tobias.fischer@qut.edu.au; if you prefer, feel free to also include the other authors) with any queries that you may have related to the paper itself.

**Comment by Autotalker** [comment]
Hi Tobias,

     Thank you for your reply. I would expect your positive, point-to-point responses to my questions [Comparing to state-of-the-art methods]. It's your right to discuss [Point out my wrong statements] or ignore.
     At this stage, please don't close this issue. I want to read your revised version [arxiv does not have a deadline].
     Thank you!
