### ISSUE TITLE
Feature matching (two files)

### ISSUE THREAD

**Issue by decadezhang** [QVPR/Patch-NetVLAD#14]
Hi, I really appreciate for the work you've done.
I ran **match_two.py**, but the score I got was only about 0.02（tokyo_query.jpg  and tokyo_db.png）. I also matched 2 same images , and the score is only 0.25. Is it because I set it wrong?Thank you again for your work and look forward to your reply！

**Comment by StephenHausler** [comment]
Hi Dacadezhang, yep that score you got is about right. For tokyo_query.jpg and tokyo_db.png, the score I get is 0.013. It is low because this is a very challenging pair of images. However it is odd that you are only getting 0.25 for the same images - I ran match_two.py with two copies of tokyo_query.jpg and got a score of 1.0. But it does depend on the pair in question. For example, if you run match_two.py on two blank white images, the score is only 0.17. This is because the local feature matching doesn't work properly because every local feature looks the same and thus there are no unique local correspondences between the two images. I suspect your result of 0.25 could be due to a same image pair that contains repetitive patterns within the image. Hope this helps.

**Comment by decadezhang** [comment]
Thanks! Thank you again for your excellent work.
