### ISSUE TITLE
Groundtruths and details of the datasets used

### ISSUE THREAD

**Issue by Anuradha-Uggi** [QVPR/Patch-NetVLAD#68]
Dear Sir,
You have done a great job. The current Github includes ground truths for Nordland, Pittsburgh 30k, and Tokyo 24/7. It would be helpful for us if you could provide the datasets and the ground truth npz files/links for RobotCar Seasons v2, Extended CMU Seasons, and Mapillary Street Level Sequences (MSLS).
Thank you very much.

**Comment by StephenHausler** [comment]
Hi @Anuradha-Uggi,
Unfortunately there are no publicly accessible GT files for the test sets of RobotCar Seasons v2 and Extended CMU Seasons, as these are challenge sets and require submission to the server on [VisualLocalization.net](https://www.visuallocalization.net/), in order to generate the results.
For MSLS, please follow these instructions to generate the ground truth:
https://github.com/QVPR/Patch-NetVLAD/blob/main/patchnetvlad/dataset_gt_files/README_how_to_calc_mapillary_gt.txt

Closing for now, but feel free to re-open if you have any more questions.
